---
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[LO,L]{\textbf{MTH-321 AB} | Spring 2026}
  \fancyhead[RO,R]{\textbf{Worksheet 13} | Pg. \thepage}
  \fancyfoot[CO,C]{}
  \usepackage{float}
  \usepackage{multirow}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
urlcolor: blue
link-citations: yes
bibliography: ../../../references.bib
csl: ../../../mbe.csl
geometry: "left=0.50in,right=0.50in,top=0.75in,bottom=0.75in"
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source(file.path("../../R/functions-mth321.R"))
```

**Name:**

**Collaborators:**

\noindent\rule{\textwidth}{1pt}
**Instructions:** Worksheets are graded mostly on completion and partially on correctness. Please write complete solutions showing explanations and key steps to the following problems, unless it says otherwise.
\noindent\rule{\textwidth}{1pt}

## Understanding the Superposition Principle

### 1. Homogeneous Case

The *superposition principle* states that for a linear 2nd-order homogeneous ODE, if $y_1$ and $y_2$ are independent solutions, then any *linear combination* $$y = c_1 y_1 + c_2 y_2$$ where $c_1$ and $c_2$ are constants, is also a solution.

Consider the homogeneous ODE $$y'' + 3y' + 2y = 0.$$ The independent solutions to the given ODE are $$y_1 = e^{-2t} \hspace{10px} \text{ and } \hspace{10px} y_2 = e^{-t}.$$

\begin{minipage}[t][\textheight-\pagetotal]{0.49\textwidth}
  \begin{itemize}
    \item[a.] Verify that $y = c_1 y_1 + c_2 y_2$ is also a solution. Discuss why this can be also the general solution.
    \vfill
    \item[c.] Write the specific solution that satisfies the initial conditions in Part (b).
    \vfill
  \end{itemize}
\end{minipage}
\hfill\vline\hfill
\begin{minipage}[t][\textheight-\pagetotal]{0.49\textwidth}
  \begin{itemize}
    \item[b.] Given the initial conditions $y(0) = 0$ and $y'(0) = 1$, show that the constants are $c_1 = -1$ and $c_2 = 1$.
    \vfill
    \item[d.] How do initial conditions help us determine the constants in a linear combination of independent solutions?
    \vfill
  \end{itemize}
\end{minipage}

\newpage

### 2. Non-Homogeneous Case

For a linear 2nd-order non-homogeneous ODE, if $y_h$ is the homogeneous solution and $y_p$ is the particular solution, then by the *superposition principle*, the general solution is of the form $$y = y_h + y_p.$$

Consider the same ODE from Problem (1) but now the right hand side is now non-zero, $$y'' + 3y' + 2y = 1.$$

We have shown that the solution to the associated homogeneous equation, that is $\displaystyle y'' + 3y' + 2y = 0$, is $$y_h = c_1 e^{-2t} + c_2 e^{-t}.$$ The proposed particular solution is $$y_p = \frac{1}{2}.$$

\begin{minipage}[t][\textheight-\pagetotal]{0.49\textwidth}
  \begin{itemize}
    \item[a.] Verify that the general solution is $y = y_h + y_p$.
    \vfill
    \item[c.] Write the specific solution that satisfies the initial conditions in Part (b).
    \vfill
  \end{itemize}
\end{minipage}
\hfill\vline\hfill
\begin{minipage}[t][\textheight-\pagetotal]{0.49\textwidth}
  \begin{itemize}
    \item[b.] Given the initial conditions $y(0) = 0$ and $y'(0) = 1$, show that the constants are $c_1 = -\frac{1}{2}$ and $c_2 = 0$.
    \vfill
    \item[d.] Why did the constants change when the equation became non-homogeneous?
    \vfill
  \end{itemize}
\end{minipage}

<!-- \newpage

## **References**

::: {#refs}
:::

<br> -->
