---
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[LO,L]{\textbf{MTH-321 AB} | Spring 2026}
  \fancyhead[RO,R]{\textbf{Worksheet 15} | Pg. \thepage}
  \fancyfoot[CO,C]{}
  \usepackage{float}
  \usepackage{multirow}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
urlcolor: blue
link-citations: yes
bibliography: ../../../references.bib
csl: ../../../mbe.csl
geometry: "left=0.50in,right=0.50in,top=0.75in,bottom=0.75in"
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source(file.path("../../R/functions-mth321.R"))
```

**Name:**

**Collaborators:**

\noindent\rule{\textwidth}{1pt}
**Instructions:** Worksheets are graded mostly on completion and partially on correctness. Please write complete solutions showing explanations and key steps to the following problems, unless it says otherwise.
\noindent\rule{\textwidth}{1pt}

## Determine the Undetermined

### 1. Revisiting the Homogeneous Case

We have been exploring a *2nd-order linear ODE with constant coefficients* of the form $$y'' + py' + qy = f(t)$$ where $\displaystyle f(t)=0$ (homogeneous) or $\displaystyle f(t)\neq 0$ (non-homogeneous). The general solution is of the form $$y = y_h + y_p$$ where $y_h$ is the homogeneous solution and $y_p$ is the particular solution --both are functions of $t$. We solved for $y_h$ using the characteristic equation. Now, we need to solve for $y_p$.

Consider the 2nd-order linear ODE with constant coefficients: $$y''+2y'-3y = f(t)$$ where $f(t)$ is some function.

\begin{minipage}[t][\textheight-\pagetotal]{0.45\textwidth}
  \begin{itemize}
    \item[a.] Determine the roots of characteristic equation for the homogeneous case, $f(t) = 0$.
    \vfill
    \item[b.] Write the homogeneous solution $y_h$.
    \vfill
  \end{itemize}
\end{minipage}
\hfill\vline\hfill
\begin{minipage}[t][\textheight-\pagetotal]{0.45\textwidth}
  \begin{itemize}
    \item[c.] Suppose $f(t) = 6$, a constant function. Let $y_p = A$ for some constant $A$. Use the verification process to determine the value of $A$. Then, write $y_p$.
    \vfill
    \item[d.] Solve for the general solution $\displaystyle y = y_h + y_p$.
    \vfill
  \end{itemize}
\end{minipage}

\newpage

### 2. The Method of Undetermined Coefficients

The goal of the method of *undetermined coefficients* is to find a suitable $y_p$ so that it satisfies the ODE.

* If $f(t)=0$, then $y_p=0$.
* If $f(t) \neq 0$ then we need to strategically pick an *Ansatz* (or a trial solution) for the particular solution.

Consider the same ODE from Problem (1), $\displaystyle y''+2y'-3y = f(t)$ where $f(t)$ is some function.

a. Let $\displaystyle f(t) = 2t - 1$. Here, we consider the Ansatz $\displaystyle y_p = A_1 t + A_0$ because the structure of $f(t)$ is a linear function. The following tasks leads you on how to solve for $y_p$. 

| Task | Show work here |
|-----|---------|
| Take derivatives of $y_p$ up to the highest order of the given ODE. |  |
|-----|---------|
| Substitute $y_p$ and its derivatives into the ODE. |  |
|-----|---------|
| Match the coefficients of like terms from the left-hand side to the right hand-side of the equation. |  |
|-----|---------|
| Solve for the unknowns. |  |
|-----|---------|
| Write the particular solution $y_p$. |  |

\begin{minipage}[t][\textheight-\pagetotal]{0.49\textwidth}
  \begin{itemize}
    \item[b.] Let $\displaystyle f(t) = e^{-3t}$. Use the same process in Part (a) to determine the particular solution, $y_p$.
    \vfill
  \end{itemize}
\end{minipage}
\hfill\vline\hfill
\begin{minipage}[t][\textheight-\pagetotal]{0.49\textwidth}
  \begin{itemize}
    \item[c.] A key step in the method of undetermined coefficients is to write the Ansatz for $y_p$. For each $f(t)$, use the table of trial solutions to write a suitable Ansatz. Do not solve for the particular solution.
      \vspace{5px}
      \begin{itemize}
        \item[i.] $\displaystyle f(t) =  e^{t} \left(t^2 + 1\right)$
        \vfill
        \item[ii.] $\displaystyle f(t) = e^{-2t} \cos{(2t)}$
        \vfill
      \end{itemize}
  \end{itemize}
\end{minipage}
