---
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[LO,L]{\textbf{MTH-321 AB} | Spring 2026}
  \fancyhead[RO,R]{\textbf{Worksheet 16} | Pg. \thepage}
  \fancyfoot[CO,C]{}
  \usepackage{float}
  \usepackage{multirow}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
urlcolor: blue
link-citations: yes
bibliography: ../../../references.bib
csl: ../../../mbe.csl
geometry: "left=0.50in,right=0.50in,top=0.75in,bottom=0.75in"
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source(file.path("../../R/functions-mth321.R"))
```

**Name:**

**Collaborators:**

\noindent\rule{\textwidth}{1pt}
**Instructions:** Worksheets are graded mostly on completion and partially on correctness. Please write complete solutions showing explanations and key steps to the following problems, unless it says otherwise.
\noindent\rule{\textwidth}{1pt}

## Using Lagrange's Method

### 1. The Method of Variation of Parameters

The goal of the *Variation of Parameters* is to find the particular solution of a *linear 2nd-order ODE with constant coefficients* in the form $$y'' + py' + qy = f(t)$$ where $p$ and $q$ are constants and $f(t)$ is some function.

Consider this *linear 2nd-order ODE with constant coefficients* $$y'' - 2y' + y = f(t)$$  where $f(t)$ is some function.

Let $\displaystyle f(t) = e^t$. The following tasks outlines the method of Variation of Parameters to find the particular solution of the 2nd-order linear non-homogeneous ODE.

| Task | Show work here |
|---|---------|
| Solve for the homogeneous solution $y_h$. Then, identify $y_1$ and $y_2$. |  |
|---|---------|
| Compute $\displaystyle W = y_1 y'_2 - y_2 y'_1$. |  |
|---|---------|
| Evaluate $\displaystyle u_1 = \int \frac{f(t)}{W} y_2 \ dt$. |  |
|---|---------|
| Evaluate $\displaystyle u_2 = \int \frac{f(t)}{W} y_1 \ dt$. |  |
|---|---------|
| Write the particular solution $\displaystyle y_p = -y_1 u_1 + y_2 u_2$. Then, simplify. |  |

The $W$ term is called the *Wronskian*.

\newpage

### 2. An Unusual Non-Homogeneous Term

Consider the same ODE from Problem (1), $\displaystyle y'' - 2y' + y = f(t)$ where $f(t)$ is some function.

Let $\displaystyle f(t) = \frac{e^{t}}{t}$. In this case, $f(t)$ is not in the list of common trial solutions for Undetermined Coefficients. The Variation of Parameters method must be used to find the particular solution.

\begin{minipage}[t][\textheight-\pagetotal]{0.49\textwidth}
  \begin{itemize}
    \item[a.] Using the homogeneous solution in Problem (1a), identify the independent solutions $y_1$ and $y_2$. Then, compute the Wronskian $$W = y_1 y'_2 - y_2 y'_1.$$
    \vfill
    \item[b.] Evaluate each integral using the Wronskian from Part (a):
      \begin{itemize}
        \item[i.] $\displaystyle u_1 = \int \frac{f(t)}{W} y_2 \ dt$
        \vfill
        \item[ii.] $\displaystyle u_2 = \int \frac{f(t)}{W} y_1 \ dt$
        \vfill
      \end{itemize}
  \end{itemize}
\end{minipage}
\hfill\vline\hfill
\begin{minipage}[t][\textheight-\pagetotal]{0.49\textwidth}
  \begin{itemize}
    \item[c.] Write the particular solution $$y_p = -y_1 u_1 + y_2 u_2.$$ Then, simplify.
    \vspace{160px}
    \item[d.] Write the general solution $\displaystyle y = y_h + y_p$. Then, solve for the specific solution using the conditions $y(1) = 1$ and $y'(1) = 0$.
    \vfill
  \end{itemize}
\end{minipage}
