---
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[LO,L]{\textbf{MTH-321 AB} | Fall 2025}
  \fancyhead[RO,R]{\textbf{Worksheet 32} | Pg. \thepage}
  \fancyfoot[CO,C]{}
  \usepackage{float}
  \usepackage{multirow}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
urlcolor: blue
link-citations: yes
bibliography: ../../../references.bib
csl: ../../../mbe.csl
geometry: "left=0.50in,right=0.50in,top=0.75in,bottom=0.75in"
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source(file.path("../../R/functions-mth321.R"))
```

**Name:**

**Collaborators:**

\noindent\rule{\textwidth}{1pt}
**Instructions:** Worksheets are graded mostly on completion and partially on correctness. Please write complete solutions showing explanations and key steps to the following problems, unless it says otherwise.
\noindent\rule{\textwidth}{1pt}

## Solve an ODE Using Laplace Transforms

### 1. Transforming a Linear 1st-Order ODE

1st-order ODEs can be solved using Laplace transforms. 

Consider a homogeneous 1st-order ODE with an initial condition, 
$$
y' + py = 0; \quad y(0) = y_0
$$ 
where $p$ is a constant. Then, we apply the notation $\mathcal{L}$ and linearity to write the ODE as 
$$
\mathcal{L}\{y'\} + p\mathcal{L}\{y\} = \mathcal{L}\{0\}.
$$
Then, we apply the table of transforms to transform the ODE from the $t$-domain to the $s$-domain.

a. Consider the homogeneous 1st-order ODE with initial conditions $\displaystyle 3y' + 2y = 0; \quad y(0) = 1$.

    The following tasks outlines the method for solving the specific solution to the given 1st-order ODE.

| Task | Show work here |
|--------|---------|
| Let $\mathcal{L}\{y(t)\} = Y(s)$. Apply the Laplace transform $\mathcal{L}$ notation. |  |
|--------|---------|
| Use the table of transforms to transform the ODE from the $t$-domain to the $s$-domain. |  |
|--------|---------|
| Solve for $\displaystyle Y(s)$.|  |
|--------|---------|
| Use the table again to apply the inverse Laplace transform $\mathcal{L}^{-1}$ to solve for $y(t)$. Make sure to use the correct notation. |  |

b. Verify the specific solution determined in Part (a) by using separation of variables or integrating factors method.
\vfill

\newpage

### 2. Transforming a Linear 2nd-Order ODE

2nd-order ODE can be solved using Laplace transforms. 

Consider a homogeneous 2nd-order ODE with initial conditions, 
$$
y'' + py' + qy = f(t); \quad y(0) = a_0, \ y'(0) = a_1.
$$ 
where $p$ and $q$ are constants. Then, we apply the notation $\mathcal{L}$ and linearity to write the ODE as 
$$
\mathcal{L}\{y''\} + p\mathcal{L}\{y'\} + q\mathcal{L}\{y\} = \mathcal{L}\{f(t)\}.
$$
Then, we apply the table of transforms to transform the ODE from the $t$-domain to the $s$-domain.

a. Consider the homogeneous 2nd-order ODE with initial conditions $y'' + 2y' - 3y = 0; \hspace{10px} y(0) = 1, \ y'(0) = 0$.

    The following tasks outlines the method for solving the specific solution to the given 2nd-order ODE.

| Task | Show work here |
|---|---------|
| Let $\mathcal{L}\{y(t)\} = Y(s)$. Apply the Laplace transform $\mathcal{L}$ notation. |  |
|---|---------|
| Use the table of transforms to transform the ODE from the $t$-domain to the $s$-domain. |  |
|---|---------|
| Solve for $\displaystyle Y(s)$. |  |
|---|---------|
| Write $Y(s)$ into a sum of partial fractions |  |
|---|---------|
| Use the table again to apply the inverse Laplace transform $\mathcal{L}^{-1}$ to solve for $y(t)$. Make sure to use the correct notation. |  |

b. Verify the specific solution determined in Part (a) by using the characteristic equation method (i.e. using the ansatz $y = e^{rt}$).
\vfill

<!-- \newpage

## **References**

::: {#refs}
:::

<br> -->
