---
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[LO,L]{\textbf{MTH-321 AB} | Spring 2026}
  \fancyhead[RO,R]{\textbf{Worksheet 12} | Pg. \thepage}
  \fancyfoot[CO,C]{}
  \usepackage{float}
  \usepackage{multirow}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
urlcolor: blue
link-citations: yes
bibliography: ../../../references.bib
csl: ../../../mbe.csl
geometry: "left=0.50in,right=0.50in,top=0.75in,bottom=0.75in"
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source(file.path("../../R/functions-mth321.R"))
```

**Name:**

**Collaborators:**

\noindent\rule{\textwidth}{1pt}
**Instructions:** Worksheets are graded mostly on completion and partially on correctness. Please write complete solutions showing explanations and key steps to the following problems, unless it says otherwise.
\noindent\rule{\textwidth}{1pt}

## Identify Solutions of 2nd-Order ODEs

### 1. Verify a Solution to a 2nd-Order ODE

Similar to verifying a solution to a 1st-order ODE, to verify a solution to 2nd-order ODE means to check if a proposed function satisfies the given ODE.

If an ODE solution is proposed, we verify it using the following process:

* Step 1: Compute the derivatives of the solution.
* Step 2: Substitute the given solution and its derivatives into the ODE.
* Step 3: Simplify and check if the resulting equation is an identity. If it is, the solution is verified.

a. Consider the ODE $\displaystyle y''+4y=0$. For the following functions, determine if they are a solution to the given ODE.

    \begin{minipage}[t][0.30\textheight]{0.45\textwidth}
      \begin{itemize}
        \item[i.] $\displaystyle y_1=\cos{(2t)}$
        \vfill
        \item[iii.] $\displaystyle y_3 = 0$
        \vfill
      \end{itemize}
    \end{minipage}
    \hfill\vline\hfill
    \begin{minipage}[t][0.30\textheight]{0.45\textwidth}
      \begin{itemize}
        \item[ii.] $\displaystyle y_2=\sin{(2t)}$
        \vfill
        \item[vi.] $\displaystyle y_4=\cos{(2t)}+\sin{(2t)}$
        \vfill
      \end{itemize}
    \end{minipage}

b. For each function, determine if they are a solution for the ODE $\displaystyle y'' - 3y' + 2y = 0$.

    \begin{minipage}[t][0.15\textheight]{0.45\textwidth}
      \begin{itemize}
        \item[i.] $\displaystyle y_1=e^{2t}$
        \vfill
      \end{itemize}
    \end{minipage}
    \hfill\vline\hfill
    \begin{minipage}[t][0.15\textheight]{0.45\textwidth}
      \begin{itemize}
        \item[ii.] $\displaystyle y_2=e^t$
        \vfill
      \end{itemize}
    \end{minipage}

\newpage

### 2. Types of Solutions to a 2nd-Order ODE

A linear 2nd-order ODE can be written in *standard form* $$y'' + p \ y' + q \ y = f$$ where $p$, $q$, and $f$ are functions of $t$ or constants.

* A *homogeneous solution* is any solution of the associated homogeneous equation given $\displaystyle f(t) = 0$.
* A *particular solution* is one specific solution to the non-homogeneous equation given $\displaystyle f(t) \ne 0$.
* An *equilibrium solution* is a constant solution where $y' = 0$ and $y'' = 0$ for all $t$.

Consider the ODE $$y'' + 3y' + 2y = 1.$$ The proposed solutions to the given ODE are $$y_1 = e^{-2t}, \hspace{10px} y_2 = e^{-t}, \hspace{10px} \text{ and } \hspace{10px} y_3 = \frac{1}{2}.$$

\begin{minipage}[t][\textheight-\pagetotal]{0.49\textwidth}
  \begin{itemize}
    \item[a.] Explain why the equation is called non-homogeneous. Then, write the associated homogeneous equation.
    \vfill
    \item[c.] Verify that $y_3$ is the particular solution.
    \vfill
  \end{itemize}
\end{minipage}
\hfill\vline\hfill
\begin{minipage}[t][\textheight-\pagetotal]{0.49\textwidth}
  \begin{itemize}
    \item[b.] Verify that $y_1$ and $y_2$ are the homogeneous solutions.
    \vfill
    \item[d.] Show that the equilibrium solution is $y = \frac{1}{2}$.
    \vfill
  \end{itemize}
\end{minipage}

<!-- \newpage

## **References**

::: {#refs}
:::

<br> -->
