---
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[LO,L]{\textbf{MTH-321 AB} | Spring 2026}
  \fancyhead[RO,R]{\textbf{Worksheet 8} | Pg. \thepage}
  \fancyfoot[CO,C]{}
  \usepackage{float}
  \usepackage{multirow}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
urlcolor: blue
link-citations: yes
bibliography: ../../../references.bib
csl: ../../../mbe.csl
geometry: "left=0.50in,right=0.50in,top=0.75in,bottom=0.75in"
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source(file.path("../../R/functions-mth321.R"))
```

**Name:**

**Collaborators:**

\noindent\rule{\textwidth}{1pt}
**Instructions:** Worksheets are graded mostly on completion and partially on correctness. Please write complete solutions showing explanations and key steps to the following problems, unless it says otherwise.
\noindent\rule{\textwidth}{1pt}

## Separate the Variables

### 1. Variable Separation

a. The following is a method to find the *exact solution* to $\displaystyle y' = 0.2y$. For now assume that $y > 0$. This assumption corresponds to the population growth context and it will make the algebra easier and hence the underlying idea clearer.
  
| Task | Show work here |
|----|---------|
| Write $y'$ as $\frac{dy}{dt}$. Then, divide both sides of $\displaystyle y' = 0.2y$ by $y$. |  |
|----|---------|
| Replace $\frac{1}{y}\frac{dy}{dt}$ with $\left[ \ln(y)\right]'$. |  |
|----|---------|
| Write integrals with respect to $t$ on both sides. |  |
|----|---------|
| Apply the Fundamental Theorem of Calculus to integrate both sides. |  |
|----|---------|
| Solve for $y$ (and remember that $y$ is actually a function, $y(t)$). |  |
|----|---------|
| Show that the *general solution* can be written as $\displaystyle y(t) = C_1e^{0.2t}$. |  |
|----|---------|

The end result, $\displaystyle y(t) = C_1 e^{0.2t}$ is called the *general solution* because it represents all possible functions that satisfy the ODE. The general solution is used to find any *specific solution*, which is a solution that corresponds to a given condition.

b. Find the *specific solution* of the ODE $\displaystyle y' = 0.2y$ with initial condition $y(0) = 1$. Note that the general solution is $\displaystyle y(t) = C_1 e^{0.2t}$, which was shown in Part (a).
\vfill

\newpage

### 2. The Process of Separation of Variables (SOV)

The method of *Separation of Variables (SOV)* can solve a 1st-order ODE written in *separable form*, $$y' = f(y)g(t)$$ where the expression $f(y)g(t)$ represents a function of $y$ and $t$, which can be factored into two distinct functions: one with $y$ and the other $t$.

We often circumvent explicit use of the chain rule and instead use a shortcut to more efficiently find the general solution. The shortcut involves treating the derivative $y'$ as a ratio $\displaystyle \frac{dy}{dt}$, "separating" the $dy$ and $dt$.
    
a. In the table below, follow the instructions to see how the shortcut works, using the equation $\displaystyle y' = -2ty$.

| Task | Show work here |
|----|---------|
| Determine $f(y)$ and $g(t)$. |
|----|---------|
| *Separate* the $dy$ from the $dt$ so that $dy$ and $y$ are on the same side. If there are $t$'s in the equation they must go on the same side as $dt$: $\displaystyle \frac{dy}{f(y)} = g(t)dt$. |  |
|----|---------|
| Integrate both sides of the equation (one side with respect to $y$, the other with respect to $t$): $\displaystyle \int \frac{1}{f(y)} dy = \int g(t) dt$. |  |
|----|---------|
| Solve for the *general solution*. |  |
|----|---------|
| Find the *specific solution* given the initial condition $y(0) = 1$. |  |

b. Consider this ODE $\displaystyle y' = \frac{t}{3y^2}$.

    Use the shortcut to determine the general solution and find the specific solution given the condition $\displaystyle y(1) = 1$.
\vfill

<!-- \newpage

## **References**

::: {#refs}
:::

<br> -->
