---
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[LO,L]{\textbf{MTH-321 AB} | Spring 2026}
  \fancyhead[RO,R]{\textbf{Worksheet 20} | Pg. \thepage}
  \fancyfoot[CO,C]{}
  \usepackage{float}
  \usepackage{multirow}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
urlcolor: blue
link-citations: yes
bibliography: ../../../references.bib
csl: ../../../mbe.csl
geometry: "left=0.25in,right=0.25in,top=0.75in,bottom=0.75in"
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source(file.path("../../R/functions-mth321.R"))
```

**Name:**

**Collaborators:**

\noindent\rule{\textwidth}{1pt}
**Instructions:** Worksheets are graded mostly on completion and partially on correctness. Please write complete solutions showing explanations and key steps to the following problems, unless it says otherwise.
\noindent\rule{\textwidth}{1pt}

## Modeling Spring-Mass

### 1. Damped and Undamped Systems

Consider the horizontal spring-mass system. The motion of the block can be modeled using a linear 2nd-order ODE of the form $$mx'' + bx' + kx = 0$$ where $x$ is the block's displacement with constant parameters, mass $m > 0$, friction coefficient $b \ge 0$ and spring constant $k > 0$.

a. Determine the characteristic equation and its roots.
\vspace{100px}

b. Determine the parameter conditions and the general solution of the homogeneous ODE for each case.

  \begin{minipage}[t][0.40\textheight]{0.49\textwidth}
    \begin{itemize}
      \item[i.] Overdamped (real distinct roots)
      \vfill
      \item[ii.] Critically damped (real repeated roots)
      \vfill
    \end{itemize}
  \end{minipage}
  \hfill\vline\hfill
  \begin{minipage}[t][0.40\textheight]{0.49\textwidth}
    \begin{itemize}
      \item[iii.] Underdamped (complex conjugate roots)
      \vfill
      \item[iv.] Undamped (imaginary roots)
      \vfill
    \end{itemize}
  \end{minipage}

\newpage

### 2. Systems with External Force

Consider the same horizontal spring-mass system shown in Problem (1). This time we add an external force acting on the mass.

a. Consider the undamped case ($b=0$), $$mx'' + kx = \cos{(\omega t)} + \sin{(\omega t)}$$ where $\omega \ne 0$ is a constant parameter. Use either undetermined coefficients or variation of parameters to solve for the particular solution. Then, determine the value of $k$ for which the frequency of the homogeneous solution matches with the non-homogeneous term of the ODE.
\vfill

b. Determine the general and specific solutions for Part (a) with initial conditions $x(0) = 1$, and $x'(0) = 0$.
\vfill
