---
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[LO,L]{\textbf{MTH-321 AB} | Spring 2026}
  \fancyhead[RO,R]{\textbf{Exam 2 Guide} | Pg. \thepage}
  \fancyfoot[CO,C]{}
  \usepackage{float}
  \usepackage{multirow}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
urlcolor: blue
link-citations: yes
bibliography: ../../../references.bib
csl: ../../../apa.csl
geometry: "left=0.50in,right=0.50in,top=0.75in,bottom=0.75in"
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Exam 2 Guide

See the Topics Schedule and Assessment sections in the Syllabus for exam schedules and procedures.

### Topics

#### 1. Basics

* **2nd-Order ODE forms.** Constant and non-constant coefficients
* **Types of solutions.** General, specific, homogeneous, and particular
*	**Verifying solutions.** 2nd-order ODEs

#### 2. Modelling Physical Systems

* **Interpreting 2nd-order ODEs.** Making meaningful 2nd-Order linear ODEs
* **Spring-Mass.** Damped and undamped harmonic oscillators
* **Spring-Mass with external force.** Forced oscillations and resonance

#### 3. Qualitative Analysis of 2nd-Order Linear ODEs

* **Existence and uniqueness.** Initial value problems and equilibriums
* **Equilibrium solutions and stability.** Stable and unstable (nodes and spirals)

#### 4. Solving 2nd-Order Linear ODEs

* **Homogeneous solutions.** Characteristic equations and its roots
* **Non-Homogeneous solutions.** Particular solutions using the following methods:
    - **Undetermined coefficients.** Create a trial solution and solve the coefficients
    - **Variation of parameters.** Using the homogeneous solutions and the Wronskian

#### 5. Order Reduction

* **Substitution.** Reduce a 2nd-order ODE into 1st-order
* **Transformation.** Convert a linear 2nd-Order ODE to a linear system of 1st-order ODEs
