---
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[LO,L]{\textbf{MTH-321 AB} | Spring 2026}
  \fancyhead[RO,R]{\textbf{Exam 3 Guide} | Pg. \thepage}
  \fancyfoot[CO,C]{}
  \usepackage{float}
  \usepackage{multirow}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
urlcolor: blue
link-citations: yes
bibliography: ../../../references.bib
csl: ../../../apa.csl
geometry: "left=0.50in,right=0.50in,top=0.75in,bottom=0.75in"
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Exam 3 Guide

See the Topics Schedule and Assessment sections in the Syllabus for exam schedules and procedures.

### Topics

#### 1. Basics

* **1st-order System of ODEs forms.** Linear vs non-linear, and homogeneous vs non-homogeneous
* **Matrix-vector form.** Converting a system of ODEs to matrix-vector form
*	**Types of solutions.**General, specific, homogeneous, and particular
*	**Verifying solutions.** 1st-order system of ODEs

#### 2. Modelling Physical Systems

* **Interpreting 1st-order system of ODEs.** Making meaningful 1st-order linear systems of ODEs
* **Spring-mass system.** Damped and undamped systems
* **Two-tank system.** Homogenous and non-homogeneous systems
* **Population dynamics.** Linear and Non-linear systems

#### 3. Qualitative Analysis of 1st-Order Linear System of ODEs

* **Existence and uniqueness.** Initial value problems and equilibriums
* **Linearization.** Using the Jacobian matrix to predict solution behaviors near an equilibrium
* **Equilibrium solutions and stability.** Node, saddle, spiral, center, and fixed points
* **Phase planes.** An $x$-$y$ plane representing two dependent variables of a system of ODEs
* **Vector fields.** Slope vectors representing the rate of change on a phase plane
* **Phase portraits.** A vector field with specific solution trajectories

#### 4. Solving 1st-Order Linear System of ODEs

*	**Homogeneous solutions.** Characteristic equations and eigensolutions in vector form:
    - **Eigenvalues.** Finding eigenvalues and use them to identify the stability of equilibriums
    - **Eigenvectors.** Finding eigenvectors and use them to determine the eigensolutions
* **Non-Homogeneous solutions.** Particular solutions as vector functions using the following methods:
    - **Undetermined coefficients.** Create a trial solution and solve the coefficients in vector form
    - **Variation of parameters.** Using the homogeneous solutions and the Wronskian in vector form
* **Graphical.** Solving for the isoclines and nullclines
