---
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[LO,L]{\textbf{MTH-321 AB} | Spring 2026}
  \fancyhead[RO,R]{\textbf{Exam 3} | Pg. \thepage}
  \fancyfoot[CO,C]{}
  \usepackage{float}
  \usepackage{multirow}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
urlcolor: blue
link-citations: yes
bibliography: ../../../references.bib
csl: ../../../apa.csl
geometry: "left=0.50in,right=0.50in,top=0.75in,bottom=0.75in"
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\begin{center}
\Large{\textbf{EXAM 3}}
\end{center}

\vfill

\begin{center}
\Large{\textbf{STEP 1: SCHEDULE YOUR SESSION}} \\
\large{\textbf{Hyperlink: \href{https://outlook.office.com/bookwithme/user/563068e7b8f84361b7e7eaf55bc932d8@up.edu/meetingtype/2TxF8nQX3kqzzkoLSdtUog2?bookingcode=4701ce29-18f8-41d1-89dd-1ad28a0580e4&anonymous&ismsaljsauthenabled&ep=mLinkFromTile}{Ordinary Differential Equation Exam}}}
\end{center}

\vfill

\begin{center}
\Large{\textbf{STEP 2: WORK ON YOUR EXAM}} \\
\large{\textbf{THE EXAM HAS TWO SETS OF PROBLEMS, X and Y}} \\
\large{\textbf{CHOOSE ONLY ONE SET AND FOLLOW THE PROMPTS}}
\end{center}

\vfill

\begin{center}
\Large{\textbf{STEP 3: SUBMIT AND SHOW UP}} \\
\large{\textbf{MAKE SURE THAT YOU FOLLOWED THE GUIDELINES}}
\end{center}

\vfill

# Guidelines^[Please review the course Syllabus for the complete Exam guidelines and assessment process.]

## Written Part

* Your work must be submitted before your scheduled session, or handed in at the start of the session.
* Your scheduled session will not proceed if your written work has not been submitted or is incomplete.

## Oral Part

* You must sign-up for a 15-minute time slot on exam days at least 24 hours in advance.
* If you had discussed an AES accommodation, you may schedule two consecutive sessions.
* You must show up to your scheduled oral part of the exam in-person and on time.
* A no-show or being late results in an automatic “M” (missed exam).

## Submission

* Submit your work in Moodle before your scheduled session.
* If necessary, you may hand in a physical copy at the start of the session.

## Collaboration and Academic Integrity Policy

* You may collaborate with your peers, but the work you submit must reflect your own.
* You may use all resources available to you, that includes your notes, books, and online resources.
* Be prepared to defend all aspects of your work.

## Extra Credit Opportunity

* Optional problems will count as an extra credit added to your homework total.

\vfill

\newpage

# X. Predicting the Motion of a Building After an Earthquake

**Description:**

Consider a building's motion after an earthquake. Ideally, a building should absorb vibrations without being too stiff (risking collapse) or swaying excessively (risking damage or collapse).

Assume small enough amplitude for the angular displacement relative to the vertical resting position. The motion of a building of fixed height after an earthquake can be modeled by the following homogeneous linear system of 1st-order ODEs: 
$$
\begin{aligned} 
\theta' & = \omega \\
\omega' & = -k \theta - 2b \omega
\end{aligned}
$$ 
where $\theta'$ is the angular velocity and $\omega'$ is the angular acceleration at time $t$. The parameter $2b \ge 0$ is the damping coefficient, and parameter $k > 0$ is the stiffness coefficient of the building.

**Written Part:**

1. Show that the $\theta$-nullcline is $\omega = 0$ and the $\omega$-nullcline are $\omega = -\frac{k}{2b} \theta$.
2. Convert the system of ODEs into matrix-vector form and identify the coefficient matrix.
3. Show that the eigenvalues of the coefficient matrix are 
  $$
  \lambda_1 = -b+\sqrt{b^2 - k} \quad \text{ and } \quad \lambda_2 = -b-\sqrt{b^2 - k},
  $$
  with corresponding eigenvectors, respectively,
  $$
  \vec{v_1} = \begin{bmatrix} -b-\sqrt{b^2 - k} \\ k \end{bmatrix} \quad \text{ and } \quad \vec{v_2} = \begin{bmatrix} -b+\sqrt{b^2 - k} \\ k \end{bmatrix}.
  $$
4. The earthquake stops at an initial condition $(\theta,\omega) = \left(\frac{1}{4},1\right)$ at $t=0$. Determine the general and specific solutions in each of the following parameter sets:
```{=latex}
\begin{center}
\begin{tabular}{cccc}
a. $\displaystyle \begin{aligned} k=& 2 \\ b=& 1 \end{aligned}$ & \hspace{30px} 
b. $\displaystyle \begin{aligned} k=& 1 \\ b=& 2 \end{aligned}$ & \hspace{30px}
c. $\displaystyle \begin{aligned} k=& 2 \\ b=& 0 \end{aligned}$ & \hspace{30px}
d. $\displaystyle \begin{aligned} k=& 1 \\ b=& 1 \end{aligned}$
\end{tabular}
\end{center}
```
5. For each case in Problem (4), use the [Phase Portrait Visualizer](https://pcnkto-alex0john-quijano.shinyapps.io/ode-visualize/){target="_blank"}\footnote{Phase Portrait Visualizer: \url{https://pcnkto-alex0john-quijano.shinyapps.io/ode-visualize/}} to draw complete and well represented phase portraits highlighting the nullclines, "straight line" solutions, and draw the specific solution curve on the vector field. Then, describe the class (or subclass) of equilibrium and its stability.
6. Use the same visualizer in Problem (5) or other forms of technology to draw graphs, with respect to $t$, of the specific solution for each case in Problem (4).

**Oral Part:**

7. Discuss the purpose of the nullclines. Then, interpret these nullclines in context.
8. Discuss the purpose of the eigenvalues and eigenvectors when determining the "straight-line" solutions and the stability of the equilibrium. Then, interpret the eigenvalues and eigenvectors in context.
9. Rank the parameter sets in Problem (4) from most to least ideal given the initial conditions, ensuring minimal swaying and fragility post-earthquake. Ideal systems exhibit motion that slowly approaches the resting position with minimal swaying, whereas less ideal systems show motion that either rapidly approaches the resting position or involves excessive swaying.

\newpage

**Optional:**

10. Let $\vec{f}(t) = \begin{bmatrix}\sin{(t)} \\ \cos{(t)} \end{bmatrix}$ be a non-homogeneous term added to the linear system. Determine the particular solution using either undetermined coefficients or variation of parameters.

\newpage

# Y. Sustaining Ecological Balance Between Lakes

**Description:**

Consider two interconnected lakes with each of its own nutrient concentrations. Excessive nutrients can promote the growth of invasive species, while insufficient nutrients can lead to species decline or extinction.

Assume a closed system of two lakes interconnected by a stream. The flow of nutrients is modeled by the following 1st-order linear system of ODEs: 
$$
\begin{aligned} 
L_1' & = - L_1 + \alpha L_2 \\
L_2' & = \beta L_1 - L_2 
\end{aligned}
$$ 
where $L_1'$ and $L_2'$ represent the change in nutrient concentrations in lakes $L_1$ and $L_2$ respectively at time $t$. The parameters $\alpha$ and $\beta$ are coefficients of the nutrient flow rates.

**Written Part:**

1. Show that the $L_1$-nullcline is $L_2 = \frac{1}{\alpha} L_1$ and the $L_2$-nullcline are $L_2 = \beta L_1$.
2. Convert the system of ODEs into matrix-vector form and identify the coefficient matrix.
3. Show that the eigenvalues of the coefficient matrix are 
  $$
  \lambda_1 = -1 + \sqrt{\alpha \beta} \quad \text{ and } \lambda_2 = -1 - \sqrt{\alpha \beta},
  $$
  with corresponding eigenvectors, respectively, 
  $$
  \vec{v_1} = \begin{bmatrix} \sqrt{\alpha} \\ \sqrt{\beta} \end{bmatrix} \quad \text{ and } \quad \vec{v_2} = \begin{bmatrix} -\sqrt{\alpha} \\ \sqrt{\beta} \end{bmatrix}.
  $$
4. The initial lake nutrient concentrations are $(L_1,L_2) = (1,2)$ at $t=0$. Determine the general and specific solutions in each of the following parameter sets:
```{=latex}
\begin{center}
\begin{tabular}{cccc}
a. $\displaystyle \begin{aligned} \alpha=& 1 \\ \beta=& 1 \end{aligned}$ & \hspace{30px} 
b. $\displaystyle \begin{aligned} \alpha=& 1 \\ \beta=& -1 \end{aligned}$ & \hspace{30px} 
c. $\displaystyle \begin{aligned} \alpha=& 2 \\ \beta=& 2 \end{aligned}$ & \hspace{30px}
d. $\displaystyle \begin{aligned} \alpha=& 0 \\ \beta=& 1 \end{aligned}$
\end{tabular}
\end{center}
```
5. For each case in Problem (4), use the [Phase Portrait Visualizer](https://pcnkto-alex0john-quijano.shinyapps.io/ode-visualize/){target="_blank"}\footnote{Phase Portrait Visualizer: \url{https://pcnkto-alex0john-quijano.shinyapps.io/ode-visualize/}} to draw complete and well represented phase portraits highlighting the nullclines, "straight line" solutions, and draw the specific solution curve on the vector field. Then, describe the class (or subclass) of equilibrium and its stability.
6. Use the same visualizer in Problem (5) or other forms of technology to draw graphs, with respect to $t$, of the specific solution for each case in Problem (4).

**Oral Part:**

7. Discuss the purpose of the nullclines. Then, interpret these nullclines in context.
8. Discuss the purpose of the eigenvalues and eigenvectors when determining the "straight-line" solutions and the stability of the equilibrium. Then, interpret the eigenvalues and eigenvectors in context.
9. Rank the parameter sets in Problem (3) from least to most ideal, ensuring nutrient concentrations to be conserved given the initial conditions. Ideal sets maintain nutrients without approaching zero or slowly approaching zero over time, while less ideal sets exhibits rapid nutrient increase or decrease.

\newpage

**Optional:**

10. Let $\vec{f}(t) = \begin{bmatrix}\cos{(t)} \\ -\sin{(t)} \end{bmatrix}$ be a non-homogeneous term added to the linear system. Determine the particular solution using either undetermined coefficients or variation of parameters.
