---
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[LO,L]{\textbf{MTH-321 AB} | Spring 2026}
  \fancyhead[RO,R]{\textbf{Worksheet 27} | Pg. \thepage}
  \fancyfoot[CO,C]{}
  \usepackage{float}
  \usepackage{multirow}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
urlcolor: blue
link-citations: yes
bibliography: ../../../references.bib
csl: ../../../mbe.csl
geometry: "left=0.25in,right=0.25in,top=0.75in,bottom=0.75in"
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source(file.path("../../R/functions-mth321.R"))
```

**Name:**

**Collaborators:**

\noindent\rule{\textwidth}{1pt}
**Instructions:** Worksheets are graded mostly on completion and partially on correctness. Please write complete solutions showing explanations and key steps to the following problems, unless it says otherwise.
\noindent\rule{\textwidth}{1pt}

## Applying Lagranges Method for Linear Systems

### 1. The Wronskian for Linear Systems

Consider this *non-homogeneous linear system of 1st-order ODEs with constant coefficients*:
$$
\begin{bmatrix}
x' \\ y'
\end{bmatrix} = 
\begin{bmatrix}
1 & -2 \\
-2 & 1
\end{bmatrix}
\begin{bmatrix}
x \\ y
\end{bmatrix} + 
\vec{f}(t).
$$
Note the non-homogeneous term $\vec{f}(t)$, a vector function of $t$, added to the system. Let $\displaystyle \vec{f}(t) = \begin{bmatrix} 3e^{2t} \\ -e^{2t}\end{bmatrix}$.

The following tasks outlines the method of *Variation of Parameters* to find the particular solution of the linear system.

| Task | Show work here |
|----|---------|
| The eigenvalues and eigenvectors of the coefficient matrix are $\lambda_1 = 3$ with $\vec{v}_1 = \begin{bmatrix} -1 \\ 1\end{bmatrix}$ and $\lambda_2 = -1$ with $\vec{v}_2 = \begin{bmatrix} 1 \\ 1\end{bmatrix}$. Construct the matrix $\displaystyle X = \begin{bmatrix} a & b \\ c & d \end{bmatrix}$ where $a$ and $c$ are the elements of $\vec{v}_1 e^{\lambda_1 t}$, and $c$ and $d$ are the elements of $\vec{v}_2 e^{\lambda_2 t}$. |  |
|----|---------|
| Determine $\displaystyle W = \text{det}(X)$. |  |
|----|---------|
| Determine $\displaystyle X^{-1} = \frac{1}{W} \begin{bmatrix} d & -b \\ -c & a\end{bmatrix}$. |  |
|----|---------|
| Determine the particular solution $\displaystyle \begin{bmatrix} x_p \\ y_p \end{bmatrix} = X \int X^{-1} \vec{f}(t) \ dt$. |  |

The matrix $W$ is the Wronskian and the result of the integral $\displaystyle X \int X^{-1} \vec{f}(t) \ dt$ is the particular solution as long as $\vec{f}(t)$ is bounded and continuous. Note that the matrix $X$ can be a constant or a function of $t$.

\newpage

### 2. An Unusual Vector Function for the Non-Homogeneous Term

The method of Variation of Parameters is useful when the non-homogeneous term of the linear system contains a function that is not in the table of common functions for the method od undetermined coefficients.

Consider this *non-homogeneous linear system of 1st-order ODEs with constant coefficients*:
$$
\begin{bmatrix}
x' \\ y'
\end{bmatrix} = 
\begin{bmatrix}
0 & 1 \\
-1 & -2
\end{bmatrix}
\begin{bmatrix}
x \\ y
\end{bmatrix} + 
\vec{f}(t).
$$
Note the non-homogeneous term $\vec{f}(t)$, a vector function of $t$, added to the system. Let $\displaystyle \vec{f}(t) = \begin{bmatrix} \ln{(t)} \\ e^{-t}\end{bmatrix}$. Because of the superposition principle, the full solution is of the form $\begin{bmatrix}x \\ y\end{bmatrix} = \begin{bmatrix}x_h \\ y_h\end{bmatrix} + \begin{bmatrix}x_p \\ y_p\end{bmatrix}$ where $\begin{bmatrix}x_h \\ y_h\end{bmatrix}$ is the homogeneous solution and $\begin{bmatrix}x_p \\ y_p\end{bmatrix}$ is the particular solution.

\begin{minipage}[t][\textheight-\pagetotal]{0.49\textwidth}
  \begin{itemize}
    \item[a.] Determine the homogeneous solution $\begin{bmatrix} x_h \\ y_h \end{bmatrix}$ using the method of eigenvalues and eigenvectors.
    \vspace{300px}
    \item[b.] Use Part (a) to construct the matrix $X$.
    \vfill
  \end{itemize}
\end{minipage}
\hfill\vline\hfill
\begin{minipage}[t][\textheight-\pagetotal]{0.49\textwidth}
  \begin{itemize}
    \item[c.] Determine the particular solution $$\begin{bmatrix} x_p \\ y_p \end{bmatrix} = X \int X^{-1} \vec{f}(t) \ dt.$$
    \vspace{260px}
    \item[d.] Write the general solution.
    \vfill
  \end{itemize}
\end{minipage}
