---
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[LO,L]{\textbf{MTH-321 AB} | Fall 2025}
  \fancyhead[RO,R]{\textbf{Worksheet 33} | Pg. \thepage}
  \fancyfoot[CO,C]{}
  \usepackage{float}
  \usepackage{multirow}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
urlcolor: blue
link-citations: yes
bibliography: ../../../references.bib
csl: ../../../mbe.csl
geometry: "left=0.50in,right=0.50in,top=0.75in,bottom=0.75in"
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source(file.path("../../R/functions-mth321.R"))
```

**Name:**

**Collaborators:**

\noindent\rule{\textwidth}{1pt}
**Instructions:** Worksheets are graded mostly on completion and partially on correctness. Please write complete solutions showing explanations and key steps to the following problems, unless it says otherwise.
\noindent\rule{\textwidth}{1pt}

## Use Laplace Transforms to Solve Non-Homogeneous ODEs

### 1. 1st-order Non-Homogeneous Linear ODEs

Non-homogeneous 1st-order ODEs can be solved using Laplace transforms. 

Consider a non-homogeneous 1st-order ODE with an initial condition, 
$$
y' + py = f(t); \quad y(0) = y_0
$$ 
where $p$ is a constant and $f(t)\ne 0$. Then, we apply the notation $\mathcal{L}$ and linearity to write the ODE as 
$$
\mathcal{L}\{y'\} + p\mathcal{L}\{y\} = \mathcal{L}\{f(t)\}.
$$
Then, we apply the table of transforms to transform the ODE from the $t$-domain to the $s$-domain.

a. Consider this ODE with an initial condition: $\displaystyle y' + 2y = t; \hspace{10px} y(0) = 1$.

    The following tasks outlines the method solving the specific solution to the given non-homogeneous 1st-order ODE.

| Task | Show work here |
|--------|---------|
| Let $\mathcal{L}\{y(t)\} = Y(s)$. Apply the Laplace transform $\mathcal{L}$ notation. |  |
|--------|---------|
| Use the table of transforms to transform the ODE from the $t$-domain to the $s$-domain. |  |
|--------|---------|
| Solve for $\displaystyle Y(s)$.|  |
|--------|---------|
| Use the table again to apply the inverse Laplace transform $\mathcal{L}^{-1}$ to solve for $y(t)$. Make sure to use the correct notation. |  |

b. Verify the specific solution determined in Part (a) by using the integrating factors method.
\vfill

\newpage

### 2. 2nd-order Non-Homogeneous Linear ODEs

Non-homogeneous 2nd-order ODEs can be solved using Laplace transform.

Consider a non-homogeneous 2nd-order ODE with an initial condition,
$$y'' + py' + qy = f(t); \hspace{10px} y(0) = a_0, \ y'(0) = a_1$$
where $p$ and $q$ are constants and $f(t) \ne 0$. Then, we apply the notation $\mathcal{L}$ and linearity to write the ODE as 
$$
\mathcal{L}\{y''\} + p\mathcal{L}\{y'\} + q\mathcal{L}\{y\} = \mathcal{L}\{f(t)\}.
$$
Then, we apply the table of transforms to transform the ODE from the $t$-domain to the $s$-domain.

a. Consider this ODE with initial conditions: $\displaystyle y'' + 2y' - 3y = t; \hspace{10px} y(0) = 1, \ y'(0) = 0$. 

    The following tasks outlines the method solving the specific solution to the given non-homogeneous 2nd-order ODE.

| Task | Show work here |
|----|---------|
| Let $\mathcal{L}\{y(t)\} = Y(s)$. Apply the Laplace transform $\mathcal{L}$ notation. |  |
|----|---------|
| Use the table of transforms to transform the ODE from the $t$-domain to the $s$-domain. |  |
|----|---------|
| Solve for $\displaystyle Y(s)$. |  |
|----|---------|
| Write $Y(s)$ into a sum of partial fractions |  |
|----|---------|
| Use the table again to apply the inverse Laplace transform $\mathcal{L}^{-1}$ to solve for $y(t)$. Make sure to use the correct notation. |  |

b. The non-homogeneous ODE in Part (a) can also be solved using the method we discussed before, which works by splitting the problem into two parts. First, we find the homogeneous solution $y_h$. Then, we find the particular solution $y_p$. By the superposition principle, the complete solution is the sum $y = y_h + y_p$.

    Using your results from Part (a), discuss which terms in your final expression correspond to the homogeneous solution $y_h$ and which terms correspond to the particular solution $y_p$.
\vfill

<!-- \newpage

## **References**

::: {#refs}
:::

<br> -->
