---
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[LO,L]{\textbf{MTH-321 AB} | Fall 2025}
  \fancyhead[RO,R]{\textbf{Worksheet 31} | Pg. \thepage}
  \fancyfoot[CO,C]{}
  \usepackage{float}
  \usepackage{multirow}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
urlcolor: blue
link-citations: yes
bibliography: ../../../references.bib
csl: ../../../mbe.csl
geometry: "left=0.50in,right=0.50in,top=0.75in,bottom=0.75in"
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source(file.path("../../R/functions-mth321.R"))
```

**Name:**

**Collaborators:**

\noindent\rule{\textwidth}{1pt}
**Instructions:** Worksheets are graded mostly on completion and partially on correctness. Please write complete solutions showing explanations and key steps to the following problems, unless it says otherwise.
\noindent\rule{\textwidth}{1pt}

## Convert Functions Using Laplace Transformations

### 1. Laplace Transforms

The *laplace transform* $\mathcal{L}\{f(t)\}$ of a *suitable* function $f(t)$ is the function $F(s)$. A function $f(t)$ can be transformed from the $t$-domain to the $s$-domain using this definition:
$$
F(s) = \int_0^{\infty} f(t) e^{(- s \ t)} \ dt.
$$

\begin{minipage}[t]{0.49\textwidth}
  \begin{itemize}
    \item[a.] Use the definition to determine the laplace transform of $f(t) = 1$. \\ \\ That is, find $F(s) = \mathcal{L}\{1\}$.
    \vspace{60px}
  \end{itemize}
\end{minipage}
\begin{minipage}[t]{0.49\textwidth}
  \begin{itemize}
    \item[b.] Use the definition to determine the laplace transform of $f(t) = e^{a \ t}$, where $a$ is a constant. \\ \\ That is, find $F(s) = \mathcal{L}\{ e^{a \ t} \}$.
    \vspace{60px}
  \end{itemize}
\end{minipage}
\vfill

You can avoid using the definition to transform a function by using the table of transforms. This allows for the conversion of common function without directly using the definition.

The laplace transform is *linear*. That is, if $F(s) = \mathcal{L}\{f(t)\}$ and $G(s) = \mathcal{L}\{g(t)\}$, then $$\mathcal{L}\{af(t) + bg(t)\} = a\mathcal{L}\{f(t)\} + b\mathcal{L}\{g(t)\} = aF(s) + bG(s), \text{ for constants } a \text{ and } b.$$

c. Let $\displaystyle f(t) = 2e^{-t} - e^{2t} + 2t^2$. Use the table to find $\displaystyle F(s) = \mathcal{L}\{f(t)\}$.
\vfill

\newpage

### 2. Inverse Laplace Transforms

The *inverse laplace transform* $\mathcal{L}\{F(s)\}$ of a *suitable* function $F(s)$ is the function $f(t)$. If $F(s) = \mathcal{L}\{f(t)\}$, then $f(t) = \mathcal{L}^{-1}\{F(s)\}$. The definition of the inverse is fairly complicated. So, we use the table to make things easier.

Finding the inverse laplace can be done by rewriting $F(s)$ to look like one of the common functions in the table. This allows for the conversion from $F(s)$ to $f(t)$ without directly using the definition.

The inverse laplace transform is *linear*. If $f(t) = \mathcal{L}^{-1}\{F(s)\}$ and $g(t) = \mathcal{L}^{-1}\{G(s)\}$, then $$\mathcal{L}^{-1}\{aF(s) + bG(s)\} = a\mathcal{L}^{-1}\{F(s)\} +  b\mathcal{L}^{-1}\{G(s)\} = af(t) + bg(t), \text{ for constants } a \text{ and } b.$$

a. Let $\displaystyle F(s) = \frac{-s^4 + 5s^3 - 4s^2 + 4s + 8}{-s^3 (s+1)(s-2)}$. 

    Use partial fraction decomposition to show that $\displaystyle F(s) = \frac{4}{s^3} + \frac{2}{s+1} - \frac{1}{s-2}$.
\vfill

b. Given the decomposed $F(s)$ in part (a), use the table of transforms to show that the 
  $$
  \mathcal{L}^{-1}\{F(s)\} = 2t^2 + 2e^{-t} - e^{2t}.
  $$
\vfill

<!-- \newpage

## **References**

::: {#refs}
:::

<br> -->
