---
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[LO,L]{\textbf{MTH-321 AB} | Spring 2026}
  \fancyhead[RO,R]{\textbf{Worksheet 9} | Pg. \thepage}
  \fancyfoot[CO,C]{}
  \usepackage{float}
  \usepackage{multirow}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
urlcolor: blue
link-citations: yes
bibliography: ../../../references.bib
csl: ../../../mbe.csl
geometry: "left=0.50in,right=0.50in,top=0.75in,bottom=0.75in"
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source(file.path("../../R/functions-mth321.R"))
```

**Name:**

**Collaborators:**

\noindent\rule{\textwidth}{1pt}
**Instructions:** Worksheets are graded mostly on completion and partially on correctness. Please write complete solutions showing explanations and key steps to the following problems, unless it says otherwise.
\noindent\rule{\textwidth}{1pt}

## Choose an Integrating Factor

### 1. The Reverse Product Rule

The following technique applies the *reverse product rule* to find the *general solution* to a 1st-order linear ODE.\footnote{This problem continues in the next page.} The tasks below solves the ODE $\displaystyle \frac{dy}{dt} - y = -t.$

| Task | Show work here |
|-----|---------|
| Use the product rule to expand $\displaystyle (yu)'$. | Line 0 |
|-----|---------|
| In the given ODE, write $\displaystyle \frac{dy}{dt}$ as $y'$. | Line 1 |
|-----|---------|
| Notice that the left-hand side of the equation in Line 1 looks a lot like the expanded product rule but is missing the function $u$. So multiply both sides by $u$, a function that we will determine shortly. | Line 2 |
|-----|---------|
| Because, so far, $u$ is an arbitrary function, we can have $u$ satisfy any differential equation that we want. Use $\displaystyle u' = -u$ to rewrite the left-hand side of Line 2 to look like Line 0. | Line 3 |
|-----|---------|
| Solve $\displaystyle u' = -u$. | Line 4 |
|-----|---------|
| Replace $u$ in the equation from Line 2 with your solution from Line 4. | Line 5 |
|-----|---------|
| Show that the equation in Line 5 can be rewritten as $\displaystyle \left(ye^{-t}\right)' = -te^{-t}$ | Line 6 |
|-----|---------|
| Write integrals with respect to $t$ on both sides of the equation in Line 6. Then, apply the Fundamental Theorem of Calculus. | Line 7 |
|-----|---------|
| Obtain the *general solution*. | Line 8 |

The function $u$ is called the *integrating factor*, a function chosen so that when the entire equation is multiplied by it, the left-hand side becomes the derivative of a product. This allows the equation to be integrated directly using the *reverse of the product rule*.

### 2. The Process of Integrating Factors

The method of *Integration Factors (IF)* is used to find the *general solution* of an ODE written in *1st-order linear form*, $$\frac{dy}{dt} + py = q,$$ where $p$ and $q$ are continuous functions of $t$.

Follow the tasks below to see how the method works to solve for the exact solution of $\displaystyle \frac{dy}{dt} = 1 - \frac{y}{1-t}$.

| Task | Show work here |
|-----|---------|
| Rewrite the given ODE into *1st-order linear form*. Then identify $p$ and $q$. |  |
|-----|---------|
| Determine the *integrating factor* $\displaystyle u = e^{\int p dt}$. Note that this is the solution to the subproblem $\displaystyle u' = up$. |  |
|-----|---------|
| Multiply $u$ in both sides of the ODE, then apply the *reverse product rule*: $\displaystyle \begin{array}{cc} u y' + upy & = uq \\ (uy)' & = uq. \end{array}$ |  |
|-----|---------|
| Integrate both sides with respect to $t$ of the equation using the Fundamental Theorem of Calculus: $\displaystyle \int (uy)' dt = \int uq dt$. |  |
|-----|---------|
| Solve for the *general solution*. |  |

<!-- \newpage

## **References**

::: {#refs}
:::

<br> -->
