---
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[LO,L]{\textbf{MTH-321 AB} | Spring 2026}
  \fancyhead[RO,R]{\textbf{Homework Set 2} | Pg. \thepage}
  \fancyfoot[CO,C]{}
  \usepackage{float}
  \usepackage{multirow}
  \usepackage{multicol}
  \usepackage{enumitem}
  \usepackage{tasks}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
urlcolor: blue
link-citations: yes
bibliography: ../../../references.bib
csl: ../../../apa.csl
geometry: "left=0.50in,right=0.50in,top=0.75in,bottom=0.75in"
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source(file.path("../../R/functions-mth321.R"))
```

**Instructions:** Homework is graded primarily on correctness and completion.

* Write your solutions on separate sheets of paper with your name written on each problem.
* Include all key steps and explanations that justify your answers, unless it says otherwise.
* Submit your written work as a `.pdf` file.
* Attach all supporting files as a `.zip` file if applicable.

\noindent\rule{\textwidth}{1pt}

## Homework Set 2

### 1. 

For each of the following autonomous ODE:

* illustrate with suitable phase diagrams the way in which the solutions and equilibriums change as the value of $r$ changes, and
* identify the precise value(s) of $r$ for which there is a either a change in the number of equilibrium solution(s) or a change in the type of equilibrium solution(s).

\begin{tasks}(3)
  \task $\displaystyle y'=(y-3)^2+r$
  \task $\displaystyle y'=y^2-ry+1$
  \task $\displaystyle y'=ry+y^3$
\end{tasks}

### 2. 

For each of the following ODE, determine which method(s) --separation of variables (SOV) or integrating factors (IF)-- could be used to find the general solution, and draw a slope field with at least three qualitatively different solution curves. Explain why such method(s) can be used. Do not find the general solution.

\begin{tasks}(3)
  \task $\displaystyle y'=2y-3e^{-t}$
  \task $\displaystyle y'=-0.2(75-y)$
  \task $\displaystyle y'=y^2+1$
  \task $\displaystyle y'=e^t y-\cos{(t)}$
  \task $\displaystyle t^2 y y' = \sqrt{1 - y^2}$
  \task $\displaystyle y' - \frac{2}{t} y = t^2$
\end{tasks}

### 3. 

Solve the following initial value problem in two ways: once using separation of variables, and once using integrating factors. $$y' = 2y+1\, ; \quad y(0)=2.$$

### 4. 

Find the general solution to the following differential equations using separation of variables or integrating factors. Give a reason as to why you used the method you chose over the other.

\begin{tasks}(3)
  \task $\displaystyle y'-2y+t = 0$
  \task $\displaystyle y' = -\frac{y}{t}+2$
  \task $\displaystyle y' = y\sin{(t)}$
  \task $\displaystyle y'-\cos{(t)}=0$
  \task $\displaystyle y' = 2(y-1)$
  \task $\displaystyle y' + 3y = 6t$
\end{tasks}

\newpage

### 5. 

Find the specific solution to the following initial value problems.

\begin{tasks}(3)
  \task $\displaystyle y' = \frac{-t}{y}; \hspace{10px} y(0)=4$
  \task $\displaystyle y' = -\sqrt[3]{y}; \hspace{10px} y(0)=27$
  \task $\displaystyle \frac{dy}{dx} = \frac{x(y-2)}{x^2+4}; \hspace{10px} y(1)=5$
  \task $\displaystyle y' = 3y; \hspace{10px} y(0)=2$
  \task $\displaystyle y' = ty^2; \hspace{10px} y(1) = 1$
  \task $\displaystyle y' + 2y = e^{-t}; \hspace{10px} y(0) = 0$
\end{tasks}

### 6.

(Exponential Decay/Growth) Solve the following application problems by showing the ODE used and its exact solution with appropriate variables and parameters/constants. If you already know the general solution, then no need to show the method used to find the general solution.

\begin{tasks}
  \task The half-life of a radioactive substance is 2 days. Find the time required for a given amount of the material to decay to $\frac{1}{10}$ of its original mass.
  \task  A radioactive material losses 25\% of its mass in 10 minutes. What is its half-life?
  \task A person deposits \$25,000 in a bank that pays 5\% per year interest, compounded continuously. The person continuously withdraws from the account at the rate of \$750 per year. Find $V(t)$, the value of the account at time $t$ after the initial deposit.
\end{tasks}

### 7.

(Newton's Law of Cooling) Solve the following application problems by showing the ODE used and its exact solution with appropriate variables and parameters/constants. If you already know the general solution, then no need to show the method used to find the general solution.

\begin{tasks}
  \task A fluid initially at $100$\textdegree C is placed outside on a day when the temperature is $-10$\textdegree C, and the temperature of the fluid drops $20$\textdegree C in one minute. Find the temperature $T(t)$ of the fluid for $t > 0$.
  \task An object is placed in a room where the temperature is $20$\textdegree C. The temperature of the object drops by $5$\textdegree C in 4 minutes and by $7$\textdegree C in 8 minutes. What was the temperature of the object when it was initially placed in the room?
  \task A cup of boiling water is placed outside at 1:00 PM. One minute later the temperature of the water is $66.67$\textdegree C. After another minute its temperature is 44.44\textdegree C. What is the outside temperature?
\end{tasks}

\newpage

### 8.

(Logistic Growth) Solve the following application problems by showing the ODE used and its exact solution with appropriate variables and parameters/constants. If you already know the general solution, then no need to show the method used to find the general solution.

\begin{tasks}
  \task A colony of bacteria is placed in a petri dish that can support at most 10,000 cells due to limited nutrients. The population starts with 200 bacteria and grows at a 30\% rate proportional to both its current size and the unused capacity of the dish. How long will it take for the colony to reach 5,000 cells?
  \task A lake can sustain up to 50,000 fish. The fish population starts at 5,000. Biologists estimate that under ideal conditions, the population would grow at a rate of 10\% per year. What is the population after 10 years?
  \task A small college initially has 200 enrolled students. The administration estimates that the maximum number of students the college can support is 2,000. The student population grows at a 5\% rate proportional to both the current number of students and the difference between the current population and the college’s capacity. How many year does it take for student population be 95\% of the capacity?
\end{tasks}

### 9.

(Mixing Problem) Solve the following application problems by showing the ODE used and its exact solution with appropriate variables and parameters/constants. If you already know the general solution, then no need to show the method used to find the general solution.

\begin{tasks}
  \task A tank initially contains 40 gallons of pure water. A solution with 1 gram of salt per gallon of water is added to the tank at 3 gal/min, and the resulting solution drains out the same rate. Find the quantity $Q(t)$ of salt in the tank at time $t > 0$.
  \task A tank initial contains $100$ liters of a salt solution with a concentration of $0.1$ g/liter. A solution with a salt concentration of $0.3$ g/liter is added to the tank at $5$ liters/min, and the resulting mixture is drained out of the same rate. Find the concentration $K(t)$ of salt in the tank as a function of $t$.
  \task Suppose water is added to a tank at $10$ gal/min, but leaks out at the rate of $\frac{1}{5}$ gal/min for each gallon in the tank. What is the smallest capacity the tank can have if the process is to continue indefinitely?
\end{tasks}

### 10. Challenge Problem

Consider the ODE $$y' = t^n \left(e^{-y} + n - 1\right)$$ where $n$ is an integer.

\begin{tasks}
  \task Classify the ordinary differential equation for cases when $n = -2$, $n = -1$, $n = 0$, and $n = 1$.
  \task Draw slope fields for each case of $n$, and draw at least three qualitatively different solutions in each.
  \task Find the general solution of the given differential equation for each case of $n$.
  \task Explain on what happens to the solutions of the differential equation as $t \to -\infty$, $t \to 0$, and $t \to +\infty$ for each case of $n$.
\end{tasks}

<!-- \newpage

## **References**

::: {#refs}
:::

<br> -->
