---
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[LO,L]{\textbf{MTH-321 AB} | Spring 2026}
  \fancyhead[RO,R]{\textbf{Worksheet 0.1} | Pg. \thepage}
  \fancyfoot[CO,C]{}
  \usepackage{float}
  \usepackage{multirow}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
urlcolor: blue
link-citations: yes
bibliography: ../../../references.bib
csl: ../../../mbe.csl
geometry: "left=0.25in,right=0.25in,top=0.75in,bottom=0.75in"
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source(file.path("../../R/functions-mth321.R"))
```

**Name:**

**Collaborators:**

\noindent\rule{\textwidth}{1pt}
**Instructions:** Worksheets are graded mostly on completion and partially on correctness. Please write complete solutions showing explanations and key steps to the following problems, unless it says otherwise.
\noindent\rule{\textwidth}{1pt}

## Review Algebra

### 1. Equations

a. Determine the solutions to the following equations.
  
\begin{minipage}{0.49\textwidth}
  \begin{itemize}
    \item[i.] $\displaystyle 2x^2 + x - 1 = 0$
    \vspace{90px}
    \item[ii.] $\displaystyle x^2 + 3x = 0$
    \vspace{90px}
  \end{itemize}
\end{minipage}
\begin{minipage}{0.49\textwidth}
  \begin{itemize}
    \item[iii.] $\displaystyle x^2 - 2x = -1$
    \vspace{90px}
    \item[iv.] $\displaystyle 3x^2 + 1 = 0$
    \vspace{90px}
  \end{itemize}
\end{minipage}

b. The following equations are false. Explain why and provide a counterexample.

\begin{minipage}{0.49\textwidth}
  \begin{itemize}
    \item[i.] $\displaystyle \sqrt{a+b} = \sqrt{a} + \sqrt{b}$
    \vspace{90px}
    \item[ii.] $\displaystyle (x + y)^2 = x^2 + y^2$
    \vspace{90px}
  \end{itemize}
\end{minipage}
\begin{minipage}{0.49\textwidth}
  \begin{itemize}
    \item[iii.] $\displaystyle \frac{x^2 - 9}{x - 3} = x - 3$
    \vspace{90px}
    \item[iv.] $\displaystyle \frac{x}{x-y} = \frac{1}{y}$
    \vspace{90px}
  \end{itemize}
\end{minipage}

\newpage

### 2. System of Equations

a. For each system of equations, solve for the values of $x$ and $y$ that satisfy both equations. Then, describe the geometry of the solution(s).

\begin{minipage}{0.49\textwidth}
  \begin{itemize}
    \item[i.] $\displaystyle \begin{aligned}2x +  y & = 10 \\ 3x - 2y & = 5\end{aligned}$
    \vspace{250px}
  \end{itemize}
\end{minipage}
\begin{minipage}{0.49\textwidth}
  \begin{itemize}
    \item[ii.] $\displaystyle \begin{aligned}2x + 4y & = 6 \\ x + 2y & = 3\end{aligned}$
    \vspace{250px}
  \end{itemize}
\end{minipage}
  
b. Express the rational function $\displaystyle f(x) = \frac{2x^3 + 3x^2 + 4x + 5}{(x-1)^2 (x^2 + 1)}$ as a sum of partial fractions.
\vfill

<!-- \newpage

## **References**

::: {#refs}
:::

<br> -->
