---
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[LO,L]{\textbf{MTH-321 AB} | Spring 2026}
  \fancyhead[RO,R]{\textbf{Worksheet 1} | Pg. \thepage}
  \fancyfoot[CO,C]{}
  \usepackage{float}
  \usepackage{multirow}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
urlcolor: blue
link-citations: yes
bibliography: ../../../references.bib
csl: ../../../mbe.csl
geometry: "left=0.25in,right=0.25in,top=0.75in,bottom=0.75in"
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source(file.path("../../R/functions-mth321.R"))
```

**Name:**

**Collaborators:**

\noindent\rule{\textwidth}{1pt}
**Instructions:** Worksheets are graded mostly on completion and partially on correctness. Please write complete solutions showing explanations and key steps to the following problems, unless it says otherwise.
\noindent\rule{\textwidth}{1pt}

## Classify ODEs and Verify Solutions

### 1. Classify ODEs

Using the table below, classify each ODE based on the following criteria:

* Order: The order of an ODE —*1st*, *2nd*, etc.— is determined by the highest derivative of the dependent variable present in the equation.
* Autonomy: An *autonomous* ODE is one where the independent variable does not explicitly appear in the equation. Otherwise, it is *non-autonomous*.
* Homogeneity: A *homogeneous* ODE can be expressed as a function of the ratio of the dependent and independent variables. If this is not possible, it is *non-homogeneous*.
* Linearity: In a *linear* ODE, the dependent variable and its derivatives appear linearly, meaning they are not an input of a non-linear function. If this is not the case, it is *non-linear*.

Fill in each column according to the specified criteria. Explanations are not required.

```{=latex}
\begin{center}
\begin{tabular}{|l|m{1.25in}|m{1.25in}|m{1.25in}|m{1.25in}|}
\hline
\textbf{ODE}                                           & \textbf{Order}    & \textbf{Autonomy} & \textbf{Homogeneity} & \textbf{Linearity} \\ \hline
\multirow{3}{*}{a. $\displaystyle \frac{dy}{dt} = 3y$} & \multirow{3}{*}{} & \multirow{3}{*}{} & \multirow{3}{*}{}    & \multirow{3}{*}{}  \\
                                                       &                   &                   &                      &                    \\
                                                       &                   &                   &                      &                    \\ \hline
\multirow{3}{*}{b. $\displaystyle y'' = 4y - \sin{(t)}$}                         & \multirow{3}{*}{} & \multirow{3}{*}{} & \multirow{3}{*}{} & \multirow{3}{*}{} \\
                                                       &                   &                   &                      &                    \\
                                                       &                   &                   &                      &                    \\ \hline
\multirow{3}{*}{c. $\displaystyle \frac{d^2 x}{dt^2} + 2 \frac{dx}{dt} + x = 0$} & \multirow{3}{*}{} & \multirow{3}{*}{} & \multirow{3}{*}{} & \multirow{3}{*}{} \\
                                                       &                   &                   &                      &                    \\
                                                       &                   &                   &                      &                    \\ \hline
\multirow{3}{*}{d. $\displaystyle ty'' + y' + ty = 0$} & \multirow{3}{*}{} & \multirow{3}{*}{} & \multirow{3}{*}{}    & \multirow{3}{*}{}  \\
                                                       &                   &                   &                      &                    \\
                                                       &                   &                   &                      &                    \\ \hline
\multirow{3}{*}{e. $\displaystyle \frac{dz}{dt} = 2t^2 + z$}                     & \multirow{3}{*}{} & \multirow{3}{*}{} & \multirow{3}{*}{} & \multirow{3}{*}{} \\
                                                       &                   &                   &                      &                    \\
                                                       &                   &                   &                      &                    \\ \hline
\multirow{3}{*}{f. $\displaystyle y'' + y^3 + \cos{(t)} = e^t$}                  & \multirow{3}{*}{} & \multirow{3}{*}{} & \multirow{3}{*}{} & \multirow{3}{*}{} \\
                                                       &                   &                   &                      &                    \\
                                                       &                   &                   &                      &                    \\ \hline
\end{tabular}
\end{center}
```

\newpage

### 2. Classify and Verify Solutions to ODEs

There are two types of *exact* solutions:

* A *general solution* is a function that involve arbitrary constants generated during integration.
* A *specific solution* is obtained by assigning values to the arbitrary constants in a general solution.

If an ODE solution is proposed, we verify it using the following process:

* Step 1: Compute the derivatives of the solution.
* Step 2: Substitute the given solution and its derivatives into the ODE.
* Step 3: Simplify and check if the resulting equation is an identity. If it is, the solution is verified.

For each of the following exact solutions, verify that it satisfies the corresponding ODE. Then, determine whether the form of the solution is *general* or *specific*.

a. Proposed Solution: $\displaystyle \hspace{5px} y(t) = e^{3t} \hspace{20px} \longrightarrow \hspace{20px}$ ODE: $\displaystyle \hspace{5px} \frac{dy}{dt} = 3y$
\vfill
b. Proposed Solution: $\displaystyle \hspace{5px} x(t) = C_1 e^{-t} + C_2 t e^{-t} \hspace{20px} \longrightarrow \hspace{20px}$ ODE: $\displaystyle \hspace{5px} \frac{d^2 x}{dt^2} + 2 \frac{dx}{dt} + x = 0$
\vfill
c. Proposed Solution: $\displaystyle \hspace{5px} y(t) = C_1 e^{2t} + C_2 e^{-2t} + \frac{\sin{(t)}}{5}  \hspace{20px} \longrightarrow \hspace{20px}$ ODE: $\displaystyle \hspace{5px} y'' = 4y - \sin{(t)}$
\vfill

<!-- \newpage

## **References**

::: {#refs}
:::

<br> -->
