---
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[LO,L]{\textbf{MTH-321 AB} | Spring 2026}
  \fancyhead[RO,R]{\textbf{Worksheet 24} | Pg. \thepage}
  \fancyfoot[CO,C]{}
  \usepackage{float}
  \usepackage{multirow}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
urlcolor: blue
link-citations: yes
bibliography: ../../../references.bib
csl: ../../../mbe.csl
geometry: "left=0.25in,right=0.25in,top=0.75in,bottom=0.75in"
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source(file.path("../../R/functions-mth321.R"))
```

**Name:**

**Collaborators:**

\noindent\rule{\textwidth}{1pt}
**Instructions:** Worksheets are graded mostly on completion and partially on correctness. Please write complete solutions showing explanations and key steps to the following problems, unless it says otherwise.
\noindent\rule{\textwidth}{1pt}

## Find Eigensolutions with Real Repeated Eigenvalues

### 1. The Independent Solution

Consider the homogeneous linear system of 1st-order ODEs: $\displaystyle \begin{aligned} x' & = y  \\ y' & = -2 \ x - 2 \sqrt{2} \ y \end{aligned}$.

This system has real repeated eigenvalues with geometric multiplicity less than the algebraic multiplicity.

\begin{minipage}[t][\textheight-\pagetotal]{0.49\textwidth}
  \begin{itemize}
    \item[a.] Show that the eigenvalue is $\lambda = -\sqrt{2}$ with algebraic multiplicity of $2$.
    \vfill
    \item[b.] Show that the corresponding eigenvector of $\lambda$ is $\displaystyle \vec{v} = \begin{bmatrix} 1 \\ -\sqrt{2} \end{bmatrix}$ with geometric multiplicity of $1$.
    \vfill
  \end{itemize}
\end{minipage}
\hfill\vline\hfill
\begin{minipage}[t][\textheight-\pagetotal]{0.49\textwidth}
  \begin{itemize}
    \item[c.] Based solely on the eigenvalue, what does this tell about the behavior of solutions around the equilibrium?
    \vfill
    \item[d.] Let $\displaystyle \vec{w}_1 = \begin{bmatrix} x \\ y \end{bmatrix}$. The independent solution is 
$$
\vec{w}_1 = \vec{v} e^{(\lambda \ t)}.
$$
where $\lambda$ is the eigenvalue with its corresponding eigenvector $\vec{v}$.
    \begin{itemize}
      \item[i.] Explain why specific solutions can only be found when the initial conditions lie on the line $y = -\sqrt{2} \ x$.
      \vfill
      \item[ii.] Explain why $\vec{w}_1$ is not the general solution.
      \vfill
    \end{itemize}
  \end{itemize}
\end{minipage}

\newpage

### 2. The General Solution with Real Repeated Eigenvalues

Consider the same linear system from Problem (1) in matrix-vector form: $\displaystyle \begin{bmatrix} x' \\ y' \end{bmatrix} = \begin{bmatrix} 0 & 1 \\ -2 & -2\sqrt{2} \end{bmatrix} \begin{bmatrix} x \\ y \end{bmatrix}$. The eigenvalue is $\lambda = -\sqrt{2}$ with algebraic multiplicity of $2$ and the corresponding eigenvector is $\displaystyle \vec{v} = \begin{bmatrix} 1 \\ -\sqrt{2} \end{bmatrix}$ with geometric multiplicity of $1$. This creates one linearly independent solution of the form $$\vec{w}_1 = \vec{v} e^{(\lambda \ t)}.$$

In order to find the general solution, we need to find another linearly independent solution of the form $$\vec{w}_2 = \left(t \ \vec{v} + \vec{u} \right) e^{(\lambda \ t)}$$ where $\vec{u}$ is the *generalized eigenvector*.

a. Given the eigenvector $\vec{v} = \begin{bmatrix} 1 \\ -\sqrt{2} \end{bmatrix}$, we need to find the generalized eigenvector $\vec{u}$. The following tasks shows you how to determine $\vec{u}$ directly from the coefficient matrix.

| Task | Show work here |
|-----------|---------|
| Set $$\left(\begin{bmatrix} 0 & 1 \\ -2 & -2\sqrt{2} \end{bmatrix} - \begin{bmatrix} \lambda & 0 \\ 0 & \lambda \end{bmatrix}\right) \vec{u} = \vec{v}$$. |  |
|-----------|---------|
| Write the equation into an augmented matrix: $$\begin{aligned} \begin{matrix} \text{row}_1 \rightarrow \\ \text{row}_2 \rightarrow \end{matrix} & \begin{bmatrix} -\lambda & 1 & 1 \\ -2 & -2\sqrt{2}-\lambda & -\sqrt{2} \end{bmatrix} \end{aligned}$$ |  |
|-----------|---------|
| Row reduce the augmented matrix into the form $$\begin{aligned} \begin{matrix} \text{row}_1 \rightarrow \\ \text{row}_2 \rightarrow \end{matrix} & \begin{bmatrix} a & b & c \\ 0 & 0 & 0 \end{bmatrix} \end{aligned}$$ where $a$, $b$, and $c$ are values left over. |  |
|-----------|---------|
| The values in $\text{row}_1$ correspond to the coefficients of the line $ax + by = c$. Write this line in parametric vector form with $s$ as the independent variable. |  |
|-----------|---------|
| To determine the vector $\vec{u}$, set $s=0$. |

Now, you have two linearly independent solutions $\vec{w}_1$ and $\vec{w}_2$ which forms a fundamental set of solutions.

\begin{minipage}[t][\textheight-\pagetotal]{0.49\textwidth}
  \begin{itemize}
    \item[b.] Use the superposition principle to write the general solution.
    \vfill
  \end{itemize}
\end{minipage}
\hfill\vline\hfill
\begin{minipage}[t][\textheight-\pagetotal]{0.49\textwidth}
  \begin{itemize}
    \item[c.] Determine the specific solution using the initial condition $(1,0)$.
    \vfill
  \end{itemize}
\end{minipage}
